package org.example.pulse_ai.session;

public enum BotState {
    MAIN_MENU,
    CONNECT_CHANNEL,
    CHANNEL_CONNECTED,
    FREE_ANALYSIS_RUNNING,
    FREE_ANALYSIS_RESULT,
    REQUEST_RUNNING,
    REQUEST_RESULT,
    VIEW_IDEAS,
    VIEW_POSTS,
    POST_PREVIEW,
    POST_EDIT,
    POST_CONFIRM,
    PAYMENT_SELECT,
    PAYMENT_PROCESSING,
    HISTORY_LIST,
    HISTORY_DETAIL,
    SETTINGS
}
