package org.example.pulse_ai.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;

/**
 * Локальная H2-БД могла быть создана Hibernate без Flyway — догоняем схему перед сидерами.
 */
@Slf4j
@Component
@RequiredArgsConstructor
@ConditionalOnProperty(name = "spring.datasource.driver-class-name", havingValue = "org.h2.Driver")
public class H2LocalSchemaPatcher {

    private final JdbcTemplate jdbc;

    @PostConstruct
    void patch() {
        exec("ALTER TABLE packages ADD COLUMN IF NOT EXISTS perk_choices_count SMALLINT NOT NULL DEFAULT 0");
        exec("ALTER TABLE packages ADD COLUMN IF NOT EXISTS includes_priority BOOLEAN NOT NULL DEFAULT FALSE");
        exec("ALTER TABLE packages ADD COLUMN IF NOT EXISTS kind VARCHAR(16) NOT NULL DEFAULT 'ANALYSIS'");
        exec("ALTER TABLE packages ADD COLUMN IF NOT EXISTS dm_quota INT NOT NULL DEFAULT 0");
        exec("ALTER TABLE packages ADD COLUMN IF NOT EXISTS parse_quota INT NOT NULL DEFAULT 0");
        exec("ALTER TABLE packages ADD COLUMN IF NOT EXISTS includes_find_audience BOOLEAN NOT NULL DEFAULT FALSE");
        exec("""
                CREATE TABLE IF NOT EXISTS user_entitlements (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    perk_code VARCHAR(32) NOT NULL,
                    uses_remaining INT,
                    granted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    expires_at TIMESTAMP WITH TIME ZONE,
                    source_payment_id BIGINT
                )""");
        exec("ALTER TABLE payments ADD COLUMN IF NOT EXISTS perks_remaining_to_pick SMALLINT NOT NULL DEFAULT 0");
        exec("ALTER TABLE generated_posts ADD COLUMN IF NOT EXISTS image_url VARCHAR(1024)");
        exec("""
                CREATE TABLE IF NOT EXISTS scheduled_posts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    channel_id BIGINT NOT NULL,
                    generated_post_id BIGINT NOT NULL,
                    final_text CLOB NOT NULL,
                    image_url VARCHAR(1024),
                    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
                    published_message_id INTEGER,
                    post_link VARCHAR(512),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        relaxEnumCheck("product_channel_posts", "rubric");
        relaxEnumCheck("product_channel_posts", "status");
        exec("""
                CREATE TABLE IF NOT EXISTS product_trusted_sources (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    label VARCHAR(128) NOT NULL,
                    source_type VARCHAR(16) NOT NULL,
                    url_or_username VARCHAR(512) NOT NULL,
                    trust_level SMALLINT NOT NULL DEFAULT 5,
                    notes CLOB,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS product_style_snapshots (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    summary CLOB NOT NULL,
                    reference_list CLOB,
                    post_samples CLOB,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS manager_usage (
                    user_id BIGINT PRIMARY KEY,
                    questions_used INT NOT NULL DEFAULT 0,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS slot_performance (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    channel_id BIGINT NOT NULL,
                    slot_key VARCHAR(48) NOT NULL,
                    sample_count INT NOT NULL DEFAULT 0,
                    avg_ratio DOUBLE PRECISION NOT NULL DEFAULT 1.0,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_slot_performance UNIQUE (channel_id, slot_key)
                )""");
        exec("ALTER TABLE published_posts ADD COLUMN IF NOT EXISTS perf_measured BOOLEAN NOT NULL DEFAULT FALSE");
        exec("ALTER TABLE published_posts ADD COLUMN IF NOT EXISTS perf_views INTEGER");
        exec("ALTER TABLE published_posts ADD COLUMN IF NOT EXISTS perf_measured_at TIMESTAMP WITH TIME ZONE");
        exec("ALTER TABLE channels ADD COLUMN IF NOT EXISTS linked_discussion_chat_id BIGINT");
        exec("ALTER TABLE channels ADD COLUMN IF NOT EXISTS lead_agent_enabled BOOLEAN NOT NULL DEFAULT FALSE");
        exec("""
                CREATE TABLE IF NOT EXISTS hot_leads (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    channel_id BIGINT NOT NULL,
                    owner_user_id BIGINT NOT NULL,
                    discussion_chat_id BIGINT NOT NULL,
                    comment_message_id BIGINT NOT NULL,
                    commenter_user_id BIGINT,
                    commenter_username VARCHAR(128),
                    commenter_name VARCHAR(256),
                    comment_text CLOB,
                    category VARCHAR(32),
                    reason VARCHAR(512),
                    comment_link VARCHAR(512),
                    notified BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_hot_lead UNIQUE (discussion_chat_id, comment_message_id)
                )""");
        exec("ALTER TABLE hot_leads ADD COLUMN IF NOT EXISTS status VARCHAR(16) NOT NULL DEFAULT 'NEW'");
        exec("ALTER TABLE hot_leads ADD COLUMN IF NOT EXISTS suggested_reply CLOB");
        exec("ALTER TABLE channels ADD COLUMN IF NOT EXISTS sales_faq CLOB");
        exec("ALTER TABLE channels ADD COLUMN IF NOT EXISTS sales_objections CLOB");
        exec("""
                CREATE TABLE IF NOT EXISTS sales_learnings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    channel_id BIGINT NOT NULL,
                    owner_user_id BIGINT NOT NULL,
                    lead_id BIGINT,
                    outcome VARCHAR(16) NOT NULL,
                    summary CLOB NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("ALTER TABLE generated_posts ADD COLUMN IF NOT EXISTS content_type VARCHAR(16) NOT NULL DEFAULT 'TEXT'");
        exec("ALTER TABLE generated_posts ADD COLUMN IF NOT EXISTS poll_options CLOB");
        exec("ALTER TABLE generated_posts ADD COLUMN IF NOT EXISTS poll_anonymous BOOLEAN NOT NULL DEFAULT FALSE");
        exec("ALTER TABLE scheduled_posts ADD COLUMN IF NOT EXISTS content_type VARCHAR(16) NOT NULL DEFAULT 'TEXT'");
        exec("ALTER TABLE scheduled_posts ADD COLUMN IF NOT EXISTS poll_options CLOB");
        exec("ALTER TABLE scheduled_posts ADD COLUMN IF NOT EXISTS poll_anonymous BOOLEAN NOT NULL DEFAULT FALSE");
        exec("""
                CREATE TABLE IF NOT EXISTS ad_watch_sources (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    owner_channel_id BIGINT,
                    source_type VARCHAR(16) NOT NULL DEFAULT 'CHAT',
                    link_or_username VARCHAR(256) NOT NULL,
                    title VARCHAR(256),
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    notes CLOB,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS ad_placements (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    owner_channel_id BIGINT,
                    target_username VARCHAR(128) NOT NULL,
                    target_title VARCHAR(256),
                    scraped_channel_id BIGINT,
                    quality_score SMALLINT,
                    quality_verdict VARCHAR(24) NOT NULL DEFAULT 'UNKNOWN',
                    quality_notes CLOB,
                    posts_last_30d INT,
                    ad_ratio_percent SMALLINT,
                    avg_views INT,
                    last_checked_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS ad_radar_hits (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    watch_source_id BIGINT,
                    hit_type VARCHAR(24) NOT NULL DEFAULT 'AD_SIGNAL',
                    snippet CLOB,
                    status VARCHAR(16) NOT NULL DEFAULT 'NEW',
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS outreach_campaigns (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    owner_channel_id BIGINT,
                    name VARCHAR(128) NOT NULL,
                    scenario VARCHAR(16) NOT NULL DEFAULT 'INVITE',
                    source_ref VARCHAR(512),
                    message_template CLOB NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
                    daily_limit INT NOT NULL DEFAULT 15,
                    sent_count INT NOT NULL DEFAULT 0,
                    reply_count INT NOT NULL DEFAULT 0,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    started_at TIMESTAMP WITH TIME ZONE
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS outreach_prospects (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    campaign_id BIGINT NOT NULL,
                    username VARCHAR(128),
                    display_name VARCHAR(256),
                    telegram_user_id BIGINT,
                    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
                    personalized_text CLOB,
                    sent_at TIMESTAMP WITH TIME ZONE,
                    replied_at TIMESTAMP WITH TIME ZONE,
                    last_error VARCHAR(512),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS outreach_monthly_usage (
                    user_id BIGINT NOT NULL,
                    month_key VARCHAR(7) NOT NULL,
                    sent_count INT NOT NULL DEFAULT 0,
                    PRIMARY KEY (user_id, month_key)
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS scout_accounts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    label VARCHAR(64) NOT NULL,
                    account_type VARCHAR(16) NOT NULL DEFAULT 'OUTREACH',
                    external_ref VARCHAR(128),
                    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
                    daily_limit INT NOT NULL DEFAULT 15,
                    sent_today INT NOT NULL DEFAULT 0,
                    last_sent_at TIMESTAMP WITH TIME ZONE,
                    last_error VARCHAR(512),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS group_parse_jobs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    campaign_id BIGINT,
                    group_link VARCHAR(512) NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
                    members_found INT NOT NULL DEFAULT 0,
                    last_error VARCHAR(512),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP WITH TIME ZONE
                )""");
        exec("ALTER TABLE outreach_prospects ADD COLUMN IF NOT EXISTS scout_account_id BIGINT");
        exec("ALTER TABLE hot_leads ADD COLUMN IF NOT EXISTS follow_up_sent BOOLEAN NOT NULL DEFAULT FALSE");
        exec("""
                CREATE TABLE IF NOT EXISTS content_plan_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    channel_id BIGINT NOT NULL,
                    title VARCHAR(512) NOT NULL,
                    topic_key VARCHAR(256) NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'SUGGESTED',
                    source_request_id BIGINT,
                    idea_id BIGINT,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS scout_action_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    scout_account_id BIGINT,
                    user_id BIGINT,
                    action VARCHAR(24) NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'OK',
                    payload VARCHAR(1024),
                    error_text VARCHAR(512),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS outreach_message_templates (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT,
                    scenario VARCHAR(16) NOT NULL DEFAULT 'INVITE',
                    name VARCHAR(128) NOT NULL,
                    body CLOB NOT NULL,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS product_releases (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    version VARCHAR(32) NOT NULL,
                    title VARCHAR(256) NOT NULL,
                    bullets CLOB NOT NULL,
                    category VARCHAR(16) NOT NULL DEFAULT 'UPDATE',
                    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
                    released_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    posted_at TIMESTAMP WITH TIME ZONE,
                    channel_post_id BIGINT,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS product_story_arcs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(256) NOT NULL,
                    premise CLOB NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
                    created_by BIGINT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    started_at TIMESTAMP WITH TIME ZONE,
                    completed_at TIMESTAMP WITH TIME ZONE
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS product_story_beats (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    arc_id BIGINT NOT NULL,
                    beat_index SMALLINT NOT NULL,
                    beat_key VARCHAR(32) NOT NULL,
                    title VARCHAR(256) NOT NULL,
                    outline CLOB NOT NULL,
                    draft_text CLOB,
                    status VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
                    channel_post_id BIGINT,
                    telegram_message_id INT,
                    post_link VARCHAR(512),
                    scheduled_for TIMESTAMP WITH TIME ZONE,
                    published_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        exec("ALTER TABLE channels ADD COLUMN IF NOT EXISTS content_style_prompt CLOB");
        exec("ALTER TABLE content_ideas ADD COLUMN IF NOT EXISTS closes_gap VARCHAR(256)");
        exec("ALTER TABLE content_ideas ADD COLUMN IF NOT EXISTS cta VARCHAR(512)");
        exec("""
                CREATE TABLE IF NOT EXISTS user_settings (
                    user_id BIGINT PRIMARY KEY,
                    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    timezone VARCHAR(64) NOT NULL DEFAULT 'Europe/Moscow'
                )""");
        exec("""
                CREATE TABLE IF NOT EXISTS ad_deals (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    owner_channel_id BIGINT,
                    placement_id BIGINT,
                    target_username VARCHAR(128) NOT NULL,
                    status VARCHAR(24) NOT NULL DEFAULT 'INTEREST',
                    pin_format VARCHAR(64),
                    price_admin_rub INT,
                    price_client_rub INT,
                    commission_percent SMALLINT NOT NULL DEFAULT 20,
                    creative_draft CLOB,
                    admin_notes CLOB,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""");
        // V29 scout chat pool + SpamBot counters (local Flyway off)
        exec("ALTER TABLE scout_accounts ADD COLUMN IF NOT EXISTS spambot_today INT DEFAULT 0 NOT NULL");
        exec("ALTER TABLE scout_accounts ADD COLUMN IF NOT EXISTS last_spambot_at TIMESTAMP WITH TIME ZONE");
        exec("""
                CREATE TABLE IF NOT EXISTS scout_target_chats (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    link VARCHAR(512) NOT NULL,
                    normalized_link VARCHAR(512) NOT NULL,
                    title VARCHAR(256),
                    kind VARCHAR(16) DEFAULT 'GROUP' NOT NULL,
                    status VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL,
                    priority INT DEFAULT 100 NOT NULL,
                    notes VARCHAR(512),
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
                )""");
        exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_scout_target_chats_norm ON scout_target_chats (normalized_link)");
        exec("""
                CREATE TABLE IF NOT EXISTS scout_chat_memberships (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    chat_id BIGINT NOT NULL,
                    scout_account_id BIGINT NOT NULL,
                    status VARCHAR(16) DEFAULT 'PENDING' NOT NULL,
                    attempts INT DEFAULT 0 NOT NULL,
                    last_error VARCHAR(512),
                    next_attempt_at TIMESTAMP WITH TIME ZONE,
                    joined_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
                )""");
        exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_scout_chat_membership ON scout_chat_memberships (chat_id, scout_account_id)");
        log.info("H2 local schema patch applied");
    }

    private void relaxEnumCheck(String table, String column) {
        try {
            jdbc.execute("ALTER TABLE " + table + " ALTER COLUMN " + column + " VARCHAR(32) NOT NULL");
        } catch (Exception ex) {
            log.debug("Could not relax {}.{}: {}", table, column, ex.getMessage());
        }
    }

    private void exec(String sql) {
        try {
            jdbc.execute(sql);
        } catch (Exception ex) {
            log.warn("H2 schema patch skipped: {} — {}", sql.lines().findFirst().orElse(sql), ex.getMessage());
        }
    }
}
